baseURL = 'https://mdfgit.github.io/MFCC/'
languageCode = 'en-us'
title = 'Mark Ferry'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 1

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 10

[[menu.main]]
identifier = 'archives'
name = 'Timeline'
url = '/archives/'
weight = 20

[[menu.main]]
identifier = 'search'
name = 'Search'
url = '/search/'
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
ShowShareButtons = true
ShowReadingTime = true

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  appleTouchIcon = "/apple-touch-icon.png"